apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: windows.knabben.github.com.1.0.0
spec:
  refName: windows.knabben.github.com
  version: 1.0.0
  releaseNotes: |
    First release of Windows GMSA package
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: wingmsa.azurecr.io/gmsa-pkg@sha256:ff5afffc292c124ba8b2502a6951c2fed00a817aa48df599deb7db01b69011f2
      template:
        - ytt:
            paths:
              - "config/"
        - kbld:
            paths:
              - "-"
              - ".imgpkg/images.yml"
      deploy:
        - kapp: {}