apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: windows.knabben.github.com.1.0.0
spec:
  refName: windows.knabben.github.com
  version: 1.0.0
  releaseNotes: |
    First release of Windows GMSA package
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: wingmsa.azurecr.io/gmsa-pkg@sha256:e91b41b6df872de2f62e94e62aab4c6db861796874759a159a9cf195b21d1fc2
      template:
        - ytt:
            paths:
              - "config/"
        - kbld:
            paths:
              - "-"
              - ".imgpkg/images.yml"
      deploy:
        - kapp: {}